### ISSUE TITLE
move discourse to webmakerprototypes

### ISSUE THREAD

**Issue by LauraHilliger** [mozilla/school-of-webmaking#69] opened 2014-03-28 11:55 UTC
hey @dirkcuys @dajbelshaw and @chadsansing were both experiencing Discourse issues, and I'm wondering if it has to do with the install being on Mofostaging? Maybe we should just go ahead and move it to training.webmakerprototypes.org/discourse ?

**Comment by dirkcuys** [comment] 2014-03-28 16:20
The problems may have been caused by me trying to setup the webmaker login. I don't mind moving it, but hosting it at a suburl may be tricky.

**Comment by LauraHilliger** [comment] 2014-03-28 16:35
so we should host at discourse.webmakerprototypes.org?

**Comment by LauraHilliger** [comment] 2014-03-31 08:03
@dirkcuys i updated this bug and am hoping we can close this today! https://bugzilla.mozilla.org/show_bug.cgi?id=989377

**Comment by LauraHilliger** [comment] 2014-04-01 11:01
here we go: Alright, new DNS is up: discourse.webmakerprototypes.org. 299 IN A  162.243.77.168

@dirkcuys can you let me know when this is done (it will mean I get to hit SEND on some invites to discourse!)

https://bugzilla.mozilla.org/show_bug.cgi?id=989377

**Comment by jbuck** [comment] 2014-04-01 16:43
Alright, new subdomain and redirect is all setup

**Comment by dirkcuys** [comment] 2014-04-01 18:34
@LauraHilliger the DNS related changes should be good now, but I'm still working on getting webmaker login sorted (https://bugzilla.mozilla.org/show_bug.cgi?id=973718).

**Comment by dirkcuys** [comment] 2014-04-07 13:10
@LauraHilliger the login works, but as it is setup right now is that it uses a webmaker account from the staging server (webmaker.mofostaging.net). Since it sounds like we're going to run things (at least for a while) at webmakerprototypes.org we should probably have the login against the real webmaker.org?

**Comment by LauraHilliger** [comment] 2014-04-07 13:20
@dirkcuys yes, we'll be at webmakerprototypes for the foreseeable future. Can you tell me what you need from our devs to get the login working at webmakerprototypes so I can ping them today?

**Comment by dirkcuys** [comment] 2014-04-07 17:33
@LauraHilliger I think there are some config updates that need to be made for it to work. I'd appreciate it if you put in the request on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=973718) on bugzilla.

**Closed as completed** 2014-04-24 22:02 UTC
Labels: bug, tech integration
